name: book_reader
description: A cross-platform e-book reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.8
  sqflite: 2.4.2
  path: 1.9.1
  file_picker: 10.3.3
  syncfusion_flutter_pdfviewer: 31.1.21
  epub_view: ^3.2.0
  docx_to_text: 1.0.1
  shared_preferences: 2.5.3
  path_provider: ^2.1.5
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true